### PR TITLE
add remote debugger for blender 2.80

### PR DESCRIPTION
**Pull request by UX3D-schmithuesen**
I didn't just overwrite the original file because some people might still use Blender 2.79.

### CODE REVIEW

**Comment by sybrenstuvel** [comment]
Thanks. Because of the copy it's hard to see what you've changed exactly. What have you changed?

Also, probably `remote_debugger_b280.py` would be a better name; it has to be a valid Python name (so no dashes or periods).

**Comment by UX3D-schmithuesen** [comment]
Thanks for the feedback!
Thinking about this again, I will try to merge the files together – if it's possible to support both Blender versions in https://github.com/KhronosGroup/glTF-Blender-IO, it should also be possible here.

**Comment by sybrenstuvel** [comment]
It's certainly possible, I'm already supporting multiple Blender versions in the Blender Cloud add-on. That's why I wanted to know the differences ;-)

**Comment by UX3D-schmithuesen** [comment]
It gives a warning when you launch it in Blender <2.79, but still works. I also increased the version to 0.4 because I thought it makes sense to mark this change with a version number.

**Comment by UX3D-schmithuesen** [comment]
The only change really is that `user_preferences` are now called `preferences`

**Comment by UX3D-schmithuesen** [comment]
@sybrenstuvel For me, this seems done now so I will just wait for further feedback :+1:

**Comment by sybrenstuvel** [comment]
Thanks for investigating where the add-on is incompatible with 2.80. I've taken the info and made the existing add-on compatible with 2.75+ (so including 2.80).

**Pull request closed without merging**
